"""Generate compact convex collision meshes for the YCB banana.

The visual banana mesh is non-convex.  MuJoCo therefore cannot use it directly
for collision: a single mesh would become one large convex hull.  This script
runs pyVHACD, then merges its fine decomposition into six ordered, convex
macro-segments.  Keeping six collision geoms captures the curve of the fruit
without making every simulation step expensive.

This is an offline asset-build tool.  Its generated OBJ files are committed to
the repository; students do not need pyVHACD to run the assignment.

Run with:
    python -m pip install '.[asset-build]'
    python scripts/generate_banana_vhacd.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pyVHACD

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/graspbench/assets/ycb/011_banana/textured.obj"
OUTPUT_DIR = SOURCE.parent / "collision"
MACRO_HULLS = 6


def load_obj(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Load the triangular vertex positions and flattened face indices of an OBJ."""
    vertices: list[list[float]] = []
    faces: list[int] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("v "):
            vertices.append([float(value) for value in line.split()[1:4]])
        elif line.startswith("f "):
            indices = [int(token.split("/")[0]) - 1 for token in line.split()[1:]]
            if len(indices) != 3:
                raise ValueError(f"Expected triangular OBJ faces, got {line!r}")
            faces.extend(indices)
    return np.array(vertices, dtype=np.float64), np.array(faces, dtype=np.uint32)


def principal_axis(vertices: np.ndarray) -> np.ndarray:
    """Return the longest principal direction, with a stable positive-y sign."""
    centered = vertices - vertices.mean(axis=0)
    _unused, _singular_values, vectors = np.linalg.svd(centered, full_matrices=False)
    axis = vectors[0]
    if axis[1] < 0:
        axis = -axis
    return axis


def macro_hulls(
    fine_hulls: list[tuple[np.ndarray, np.ndarray]], source_vertices: np.ndarray
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Merge ordered VHACD output into a few curved, collision-friendly parts."""
    axis = principal_axis(source_vertices)
    centers = np.array([vertices.mean(axis=0) for vertices, _faces in fine_hulls])
    order = np.argsort(centers @ axis)
    groups = np.array_split(order, MACRO_HULLS)
    merged: list[tuple[np.ndarray, np.ndarray]] = []

    for group in groups:
        vertices: list[np.ndarray] = []
        faces: list[np.ndarray] = []
        vertex_offset = 0
        for index in group:
            hull_vertices, hull_faces = fine_hulls[int(index)]
            vertices.append(hull_vertices)
            # pyVHACD emits VTK-style cells: [3, i, j, k] for every triangle.
            cells = hull_faces.reshape(-1, 4)
            if not np.all(cells[:, 0] == 3):
                raise RuntimeError("pyVHACD returned a non-triangular hull")
            faces.append(cells[:, 1:] + vertex_offset)
            vertex_offset += len(hull_vertices)
        merged.append(
            (
                np.concatenate(vertices, axis=0),
                np.concatenate(faces, axis=0).astype(np.uint32, copy=False).reshape(-1),
            )
        )
    return merged


def write_obj(path: Path, vertices: np.ndarray, faces: np.ndarray) -> None:
    """Write a triangulated collision OBJ without visual materials or UVs."""
    lines = ["# Generated by scripts/generate_banana_vhacd.py; do not edit manually."]
    lines.extend(f"v {x:.9g} {y:.9g} {z:.9g}" for x, y, z in vertices)
    triangles = faces.reshape(-1, 3)
    lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in triangles)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    vertices, faces = load_obj(SOURCE)
    fine_hulls = pyVHACD.compute_vhacd(vertices, faces)
    if len(fine_hulls) < MACRO_HULLS:
        raise RuntimeError(f"VHACD only returned {len(fine_hulls)} hulls, need {MACRO_HULLS}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUTPUT_DIR.glob("banana_vhacd_*.obj"):
        stale.unlink()

    merged = macro_hulls(fine_hulls, vertices)
    for index, (hull_vertices, hull_faces) in enumerate(merged):
        destination = OUTPUT_DIR / f"banana_vhacd_{index:02d}.obj"
        write_obj(destination, hull_vertices, hull_faces)
        print(
            f"{destination.relative_to(ROOT)}: "
            f"{len(hull_vertices)} vertices, {len(hull_faces) // 3} triangles"
        )
    print(f"Generated {len(merged)} convex macro-hulls from {len(fine_hulls)} VHACD hulls.")


if __name__ == "__main__":
    main()
